c1 = float(input())
c2 = float(input())
c3 = float(input())
c4 = float(input())
c5 = float(input())
nfz= round(((c2 + c3 + c4)/3) * (((c1 + c5)/2) / 100),2)
nf = round(((c1 + c2 + c3 + c4 + c5 ) / 5),2)
print ("Nota Final Z:",nfz)
print ("Nota Final tradicional:",nf)

